name: Cypress Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress.io
        uses: cypress-io/github-action@v5.3.0
        with:
            start: npx cypress run
      - name: allure-html-reporter-github-pages
        uses: PavanMudigonda/allure-html-reporter-github-pages@494af460cf5d0c0a0a4e48f800fc3fe48891cf21
        with:
            start: ALLURE RESULTS JSON FILE
         
  
